//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CroMed
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoslovniSubjekt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PoslovniSubjekt()
        {
            this.Dokument = new HashSet<Dokument>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Kontakt { get; set; }
        public string Adresa { get; set; }
        public string OIB { get; set; }
        public int VrstaSubjekta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokument> Dokument { get; set; }
        public virtual VrstaSubjekta VrstaSubjekta1 { get; set; }

    }
}
