//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CroMed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvodi()
        {
            this.StavkeDokumenta = new HashSet<StavkeDokumenta>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
        public int Kategorija { get; set; }
        public int StanjeZaliha { get; set; }
        public Nullable<double> NabavnaCijena { get; set; }
        public Nullable<double> ProdajnaCijena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkeDokumenta> StavkeDokumenta { get; set; }
        public virtual Kategorija Kategorija1 { get; set; }

    }
}
