//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CroMed
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromjeneStanjaDokumenta
    {
        public int Dokument { get; set; }
        public int StanjeDokumenta { get; set; }
        public Nullable<System.DateTime> DatumPromjene { get; set; }
        public string Napomena { get; set; }
        public int Zaposlenik { get; set; }
    
        public virtual Dokument Dokument1 { get; set; }
        public virtual StanjeDokumenta StanjeDokumenta1 { get; set; }
        public virtual Zaposlenik Zaposlenik1 { get; set; }
    }
}
