//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CroMed
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkeDokumenta
    {
        public int Dokument { get; set; }
        public int Proizvod { get; set; }
        public int Kolicina { get; set; }
        public Nullable<double> Rabat { get; set; }
    
        public virtual Dokument Dokument1 { get; set; }
        public virtual Proizvodi Proizvodi { get; set; }

    }
}
